
spring:
  application:
    name: item-service
    
server:
  port: 8001
  
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
            #拉取注册信息间隔时间，默认 30 秒
    registry-fetch-interval-seconds: 30
  instance:
  #心跳间隔时间，默认 30 秒   
    lease-renewal-interval-in-seconds: 30  

